#ifndef __VERSION_H__
#define __VERSION_H__

#define LOCALE 2052
#define CHARSETID 936
#define UNILOGO_MAJOR_VERSION 2
#define UNILOGO_MINOR_VERSION 1
#define UNILOGO_MICRO_VERSION 4
#define UNILOGO_VERSION L"2.1.4"

#define LOCALIZED_UNILOGO_FILE_DESCRIPTION L"The UniLogo IDE"
#define LOCALIZED_GENERAL_PRODUCTNAME   L"UniLogo"
#define LOCALIZED_ABOUTUNI_VERSION L"Vsersion"

#endif
